spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_rate?useSSL=false
    username: postgres
    password: super
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: warn
  file:
    name: log/exchangeRate.log

import-service:
  exchanger:
    name: "exchangeRate"
    key: "eb117dcb0a5f800fe8c213c1"
    url: "https://v6.exchangerate-api.com/v6"